### ISSUE TITLE
Missing syntax for the '.include' keyword and the float register

### ISSUE THREAD

**Issue by 21j2jw9ssa** [XavierCooney/mipsy-editor-features#2]
![problem_20230414_1_include syntax](https://user-images.githubusercontent.com/121330378/232012945-0f3a7de9-23b1-499b-9da8-ba941e96f062.png)
![problem_20230414_2_register f12](https://user-images.githubusercontent.com/121330378/232013007-2ffc91b3-a566-4285-ae90-e69ce3bec44c.png)
![problem_20230414_3_errors](https://user-images.githubusercontent.com/121330378/232013030-ef1dc0d6-f60d-4eb0-824f-e973745bd295.png)

While using the two files, 'hybrid_Fibonacci.s' and 'module_IO.s', which are on the same file path and are error-free (as they can run on MARS), to code, there are two problems:
1. The 'hybrid_Fibonacci.s' file: intended to reference the code of 'module_IO.s' using the MIPS keyword '.include', it is viewed as a parse failure.
2. The 'module_IO.s' file: $f12, which is one of the MIPS registers to store floats, is viewed as a unknown register.

**Comment by XavierCooney** [comment]
Hi there, this extension is designed specifically for the mipsy emulator (https://github.com/insou22/mipsy), and so unfortunately doesn't support syntax found in other assemblers/emulators such as MARS.
